apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-ssm-operator
  namespace: kube-system
  labels:
    app: aws-ssm-operator
    ssm.aws/release: v0.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aws-ssm-operator
  template:
    metadata:
      labels:
        name: aws-ssm-operator
    spec:
      serviceAccountName: aws-ssm-operator
      containers:
        - name: aws-ssm-operator
          image: toversus/aws-ssm-operator:v0.1.0
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - aws-ssm-operator
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 5
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "aws-ssm-operator"
            - name: AWS_REGION
              value: "ap-northeast-1"
